apiVersion: apps/v1
kind: Deployment
metadata:
  name: icesi-backend
  namespace: icesi-health
  labels:
    app: icesi-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: icesi-backend
  template:
    metadata:
      labels:
        app: icesi-backend
    spec:
      containers:
      - name: icesi-backend
        image: cr152828132813.azurecr.io/icesi-backend
        ports:
        - containerPort: 8089
        env:
          - name: DATABASE_URL
            value: "http://admin:icesi@$(MY_COUCHDB_SERVICE_HOST):5984"
            
---

apiVersion: v1
kind: Service
metadata:
  name: icesi-backend
  namespace: icesi-health
spec:
  selector:
    app: icesi-backend
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP
